version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    container_name: mongoExpress
    restart: always
    ports:
      - "8088:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=economyMinistry
    volumes:
      - .\eco_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8099:8080"
volumes:
  data: {}
networks:
  default:
    name: mongodb_network
