server:
  port: 8081
spring:
  application:
    name: Economy
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5000/economyMinistry
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
